[build.environment]
  NODE_VERSION = "18.18.0"  # or any supported version
  
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-cache-core"
